import Foundation

// Shared product copy; platform names are adapted by the native presentation layer.

public enum L10n {
    public static func allStrings(language: AppLanguage) -> [String: String] {
        Dictionary(uniqueKeysWithValues: (tables[.english] ?? [:]).keys.map { ($0, string($0, language: language)) })
    }
    public static func string(_ key: String, language: AppLanguage) -> String {
        let resolved: AppLanguage
        switch language {
        case .system:
            resolved = Locale.preferredLanguages.first?.hasPrefix("zh") == true
                ? .simplifiedChinese
                : .english
        case .english, .simplifiedChinese:
            resolved = language
        }
        return tables[resolved]?[key] ?? tables[.english]?[key] ?? key
    }

    private static let tables: [AppLanguage: [String: String]] = [
        .english: [
            "provider_manager_title": "Service providers",
            "provider_new": "Add provider",
            "provider_saved": "Saved providers",
            "provider_name": "Name",
            "provider_name_placeholder": "e.g. My API service",
            "provider_key_placeholder": "Enter the API key",
            "provider_keep_key": "Leave blank to keep the saved key",
            "provider_responses_notice": "Requires OpenAI Responses API (/responses). Third-party providers are supported. Fetching models does not verify Responses compatibility.",
            "provider_models": "Models",
            "provider_fetch": "Fetch models",
            "provider_validate": "Verify connection",
            "provider_validation_hint": "Sends a short request using the selected model and effort (up to 512 output tokens). Charges may apply.",
            "provider_validation_success": "Responses request succeeded for this model. Streaming and tool calls have not been tested.",
            "provider_validation_incomplete": "The Responses request did not complete. Check model access and effort; this check allows up to 512 output tokens.",
            "provider_management_unavailable": "Provider management is unavailable in this runtime.",
            "provider_search": "Search model ID or name (fuzzy match)",
            "provider_sort": "Sort models",
            "provider_sort_custom": "Custom order",
            "provider_manual_id": "Or enter a model ID manually",
            "provider_add_model": "Add model",
            "provider_default_model": "Default model",
            "provider_set_default": "Set as default",
            "provider_enable_model": "Enable this model",
            "provider_move_up": "Move up",
            "provider_move_down": "Move down",
            "provider_effort_default": "Model default (leave empty)",
            "provider_effort_options": "Advertised options",
            "provider_effort_manual_hint": "The model list did not advertise effort options. Leave empty for the model default, or enter an effort value documented by your service.",
            "provider_effort_advertised_hint": "Use an advertised option or leave empty for the model default.",
            "provider_fetch_hint": "Fetch models or enter an ID manually. The list and order apply to this switcher.",
            "provider_no_match": "No matching models.",
            "provider_storage_notice": "The API key is saved in your private local Codex configuration. Saving adds the provider; switch to it when ready.",
            "provider_save": "Save provider",
            "provider_invalid_url": "Enter an HTTPS API base URL without credentials, query or fragment; HTTP is allowed for localhost.",
            "provider_invalid_key": "Enter an API key, or keep a valid saved key.",
            "provider_empty_name": "Enter a provider name.",
            "provider_no_models": "The service returned an empty model list. You can enter an ID manually.",
            "provider_select_default": "Enable a model and choose it as the default.",
            "provider_edit_active": "Switch to another account or provider before editing the active provider.",
            "provider_invalid_response": "The service returned an invalid model or configuration response.",
            "provider_redirect_refused": "The model endpoint redirected. Enter the final API base URL to keep the key on the intended server.",
            "provider_pagination_failed": "Model pagination did not advance. The list was not imported.",
            "provider_fetch_cancelled": "Fetching models was cancelled.",
            "switch_managed_provider_body": "Codex Desktop will restart. Finish or stop running tasks and complete any quit dialog. This provider's saved default model and thinking setting will be applied. Existing conversations keep their own settings.",
            "return_saved_model_notice": "The previously saved OpenAI model and thinking settings will be restored.",
            "settings_general": "General",
            "settings_updates": "Software Update",
            "update_available": "Version %@ available",
            "update_action": "Update…",
            "update_installing": "Installing…",
            "current_version": "Version %@",
            "check_for_updates": "Check for Updates",
            "automatically_check_updates": "Check for updates automatically",
            "update_check_hint": "Checks hourly. A blue dot indicates a new version.",
            "update_check_failed": "Update check failed.",
            "usage": "Usage",
            "five_hour": "5h",
            "weekly": "7d",
            "usage_unavailable": "Usage unavailable",
            "left": "% left",
            "resets": "Resets",
            "manage": "Manage Accounts",
            "settings": "Settings",
            "quit": "Quit",
            "switch_title": "Switch to %@?",
            "switch_body": "Codex Desktop will close and reopen. Finish or stop running Desktop tasks first. If Desktop asks to quit, complete its quit dialog. Switching stops if Desktop cannot exit normally. Existing CLI sessions stay open; new CLI sessions use the selected account.",
            "cancel": "Cancel",
            "switch": "Switch Account",
            "switch_account": "Switch Account",
            "providers": "Configured Providers",
            "configured_provider": "Configured provider",
            "native_api_login": "API key login",
            "credential_in_use": "Login in use",
            "native_api_storage_notice": "OpenAI API sign-in is saved separately on this computer so you can switch back. Saved ChatGPT accounts are kept separate. The model setting is kept; choose a compatible model if needed.",
            "switch_provider_title": "Switch to %@?",
            "switch_provider": "Switch Provider",
            "switch_provider_body": "Codex Desktop will restart with this provider. Finish or stop running Desktop tasks first and complete any quit dialog. Switching stops if Desktop cannot exit normally. Existing CLI sessions stay open. The switcher does not choose a model or manage the model list. Choose a compatible model in Desktop; if it is missing, configure it in Codex first. Existing conversations are not migrated.",
            "advanced": "Advanced",
            "enable_provider_switching": "Enable provider switching",
            "provider_setup_notice": "Add services and manage their models from Manage accounts. This switch controls whether providers appear in the account list; turning it off does not change the active provider.",
            "return_account_model_notice": "The model setting is kept. If your custom provider used a different model ID, select a supported ChatGPT model in Desktop before sending a message. A custom model catalog may also need to be changed in Codex.",
            "accounts": "Accounts",
            "back": "Back",
            "add_account": "Add Account",
            "cancel_add_account": "Cancel Adding Account",
            "remove": "Remove",
            "active": "Active",
            "remove_title": "Remove %@?",
            "remove_body": "This removes only the saved local profile from this Mac.",
            "launch_at_login": "Launch at Login",
            "launch_at_login_requires_approval": "Approval is required in System Settings.",
            "launch_at_login_unavailable": "macOS could not find this Login Item.",
            "open_system_settings": "Open System Settings",
            "show_menu_bar_percentage": "Show Percentage in Menu Bar",
            "show_five_hour_usage": "Show 5-hour Usage",
            "language": "Language",
            "system_default": "System Default",
            "english": "English",
            "simplified_chinese": "简体中文",
            "sign_in_hint": "A browser window will open for Codex sign-in.",
            "sign_in_pending_hint": "Waiting for browser sign-in. Closing the browser tab does not cancel this step. Cancel here to start again.",
            "no_accounts": "No saved accounts",
            "ok": "OK",
            "operation_failed": "Operation failed",
            "switch_failed": "Account switch failed",
            "register_current_account": "Register Current Account",
            "active_unconfirmed": "Active account could not be confirmed",
            "switched_reopen_title": "Account switched",
            "switched_reopen_message": "The selected account is active, but Codex Desktop could not be reopened. Open Codex manually to continue.",
            "provider_switched_reopen_message": "The selected provider is active, but Codex Desktop could not be reopened. Open Codex manually to continue.",
        ],
        .simplifiedChinese: [
            "provider_manager_title": "服务商",
            "provider_new": "添加服务商",
            "provider_saved": "已保存的服务商",
            "provider_name": "名称",
            "provider_name_placeholder": "例如：我的 API 服务",
            "provider_key_placeholder": "输入 API Key",
            "provider_keep_key": "留空保留已保存的密钥",
            "provider_responses_notice": "服务商需支持 OpenAI Responses API（/responses），可以是第三方服务。获取模型成功不代表 Responses 调用可用。",
            "provider_models": "模型",
            "provider_fetch": "获取模型",
            "provider_validate": "验证连接",
            "provider_validation_hint": "使用所选模型和 thinking 发送简短请求（最多 512 输出 token），可能产生少量费用。",
            "provider_validation_success": "所选模型的 Responses 请求成功。流式输出和工具调用尚未验证。",
            "provider_validation_incomplete": "Responses 请求未完成。请检查模型权限和 thinking 设置；本次验证最多使用 512 输出 token。",
            "provider_management_unavailable": "当前运行时无法管理服务商。",
            "provider_search": "模糊搜索模型 ID 或名称",
            "provider_sort": "排序",
            "provider_sort_custom": "自定义顺序",
            "provider_manual_id": "或手动输入模型 ID",
            "provider_add_model": "添加模型",
            "provider_default_model": "默认模型",
            "provider_set_default": "设为默认模型",
            "provider_enable_model": "启用此模型",
            "provider_move_up": "上移",
            "provider_move_down": "下移",
            "provider_effort_default": "跟随模型默认值（留空）",
            "provider_effort_options": "服务商提供的选项",
            "provider_effort_manual_hint": "模型列表没有提供 effort 选项。留空使用模型默认值，也可填写服务商文档支持的 effort 值。",
            "provider_effort_advertised_hint": "选择服务商提供的选项，或留空使用模型默认值。",
            "provider_fetch_hint": "获取模型或手动添加 ID。勾选列表和排序用于本切换器。",
            "provider_no_match": "没有匹配的模型。",
            "provider_storage_notice": "API Key 保存到本机受文件权限保护的 Codex 配置。保存后添加服务商，准备好后再切换。",
            "provider_save": "保存服务商",
            "provider_invalid_url": "请输入 HTTPS API Base URL，不包含用户名、密码、查询参数或片段；本地地址可用 HTTP。",
            "provider_invalid_key": "请输入 API Key，或保留有效的已保存密钥。",
            "provider_empty_name": "请输入服务商名称。",
            "provider_no_models": "服务返回的模型列表为空，可以手动输入模型 ID。",
            "provider_select_default": "请启用一个模型并将其设为默认模型。",
            "provider_edit_active": "请先切换到其他账号或服务商，再编辑当前服务商。",
            "provider_invalid_response": "服务返回的模型或配置数据格式无效。",
            "provider_redirect_refused": "模型接口发生重定向。请填写最终 API Base URL，以确保密钥只发送到指定服务器。",
            "provider_pagination_failed": "模型分页未正常推进，列表未导入。",
            "provider_fetch_cancelled": "已取消获取模型。",
            "switch_managed_provider_body": "Codex Desktop 将重新启动。请先完成或停止正在运行的任务，并处理退出提示。将应用此服务商保存的默认模型和 thinking 设置。现有对话保留各自的设置。",
            "return_saved_model_notice": "将恢复此前保存的 OpenAI 模型和 thinking 设置。",
            "settings_general": "通用",
            "settings_updates": "软件更新",
            "update_available": "发现新版本 %@",
            "update_action": "更新…",
            "update_installing": "正在安装…",
            "current_version": "当前版本 %@",
            "check_for_updates": "检查更新",
            "automatically_check_updates": "自动检查更新",
            "update_check_hint": "每小时检查一次，有新版本时显示蓝点。",
            "update_check_failed": "检查更新失败。",
            "usage": "用量",
            "five_hour": "5 小时",
            "weekly": "7 天",
            "usage_unavailable": "用量暂不可用",
            "left": "% 剩余",
            "resets": "重置于",
            "manage": "管理账号",
            "settings": "设置",
            "quit": "退出应用",
            "switch_title": "切换到 %@？",
            "switch_body": "Codex Desktop 将关闭并重新打开。请先完成或停止正在运行的 Desktop 任务。如果 Desktop 显示退出提示，请处理该提示；无法正常退出时会停止切换。现有 CLI 会话保持运行，新 CLI 会话将使用所选账号。",
            "cancel": "取消",
            "switch": "切换账号",
            "switch_account": "切换账号",
            "providers": "已配置的提供商",
            "configured_provider": "已配置的提供商",
            "native_api_login": "API key 登录",
            "credential_in_use": "登录凭据使用中",
            "native_api_storage_notice": "OpenAI API 登录将单独保存在本机，便于以后切回。已保存的 ChatGPT 账号与其分开保存。模型设置会保留，必要时请选择兼容模型。",
            "switch_provider_title": "切换到 %@？",
            "switch_provider": "切换提供商",
            "switch_provider_body": "Codex Desktop 将使用此提供商重新启动。请先完成或停止正在运行的 Desktop 任务，并处理退出提示；无法正常退出时会停止切换。现有 CLI 会话保持运行。切换器不会选择模型或管理模型列表。请在 Desktop 中选择兼容模型；如果列表中没有，请先在 Codex 中配置。现有对话不会迁移。",
            "advanced": "高级",
            "enable_provider_switching": "启用提供商切换",
            "provider_setup_notice": "在管理账号中添加服务商、选择和排序模型。此开关控制账号列表是否显示服务商，关闭后不改变当前服务商。",
            "return_account_model_notice": "模型设置将保留。如果自定义提供商使用了不同的模型 ID，请先在 Desktop 中选择 ChatGPT 支持的模型再发送消息。自定义模型目录也可能需要在 Codex 中更改。",
            "accounts": "账号",
            "back": "返回",
            "add_account": "添加账号",
            "cancel_add_account": "取消添加账号",
            "remove": "移除",
            "active": "当前",
            "remove_title": "移除 %@？",
            "remove_body": "此操作只会移除这台 Mac 上保存的本地账号档案。",
            "launch_at_login": "登录时自动启动",
            "launch_at_login_requires_approval": "需要在系统设置中允许此登录项。",
            "launch_at_login_unavailable": "macOS 找不到此登录项。",
            "open_system_settings": "打开系统设置",
            "show_menu_bar_percentage": "在菜单栏显示百分比",
            "show_five_hour_usage": "显示 5 小时用量",
            "language": "语言",
            "system_default": "跟随系统",
            "english": "English",
            "simplified_chinese": "简体中文",
            "sign_in_hint": "将打开浏览器进行 Codex 登录。",
            "sign_in_pending_hint": "正在等待浏览器登录。关闭认证标签页不会取消添加；可在此取消后重新添加。",
            "no_accounts": "暂无已保存账号",
            "ok": "好",
            "operation_failed": "操作失败",
            "switch_failed": "账号切换失败",
            "register_current_account": "登记当前登录账号",
            "active_unconfirmed": "无法确认当前账号",
            "switched_reopen_title": "账号已切换",
            "switched_reopen_message": "所选账号已经生效，但 Codex Desktop 未能重新打开。请手动打开 Codex 继续使用。",
            "provider_switched_reopen_message": "所选提供商已经生效，但 Codex Desktop 未能重新打开。请手动打开 Codex 继续使用。",
        ],
    ]
}
